spring: 
 h2:
    console:
      enabled: true
      path: /console
      settings:
       web-allow-others: true
 datasource:
    url: jdbc:h2:mem:reservas 
    username: admin
    password: alex
    driverClassName: org.h2.Driver  
 jpa:
    database-platform: org.hibernate.dialect.H2Dialect     
    generate-ddl: true
    hibernate:  
      ddl-auto: update
 main:
    allow-bean-definition-overriding: true         
 thymeleaf:
    prefix: file:src/main/resources/templates/
    cache: false
    
server:
  port: 8080

logging:  level:     root: info  pattern:    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:    name:  logs/mylog.log 

      